### ISSUE TITLE
Issue with cordova 5.0 

### ISSUE THREAD

**Issue by floorvest** [Wizcorp/phonegap-facebook-plugin#1000]
Hey, i using this plugin for cordova 4.3.0 and still okay, but when i upgrade to 5.0 there always error when build android.
![image](https://cloud.githubusercontent.com/assets/7950781/7532945/e7211dc6-f596-11e4-999d-56539c79e889.png)

can you help me?

**Comment by kaansoral** [comment]
It's not your problem, and from my impression of the state of this plugin, it will likely not get solved for months

It happens because another plugin you use imports the same android/java library and they clash

An easy/dirty fix is to not use one of these plugins

(There might be a manual fix that handles the clash, however I'm not aware of it)

**Comment by prabowo24** [comment]
You were right, i create new project with only install this plugin and they working now..

so how can i search the plugin who made clash? i'm noob when to native..

**Comment by kaansoral** [comment]
Simplest way: Add plugins one by one, test after you add each plugin
There are faster ways, but this is the simplest

**Comment by floorvest** [comment]
it's look like who made error is ionic android@4.0.0, i'm using ionic and when i trying to using that version, this plugin facebook never want to build.

but really thanks for helping man :+1:  thank you so much and sorry if my english really bad.. :)
