### ISSUE TITLE
Cannot get plugin to connect to native FB app even with deep linking enabled

### ISSUE THREAD

**Issue by crosstechnology** [Wizcorp/phonegap-facebook-plugin#1131]
Hey! First of all, thank you for this plugin it has been working fantastically so far. I've done a heap of searching both on the GitHub issues/FAQ pages and over numerous forums

My app is able to login/logout using facebook perfectly fine, with one small issue. Every time a user is prompted to login on iOS it is opening the facebook authorisation page in Safari. I would much prefer for it to open a facebook authorisation dialogue "in app" provided that the user has the native facebook app on their device.

I saw in the troubleshooting/FAQ that the suggested answer was to enable "deep linking" in the settings page of the developer dashboard. Unfortunately I have done this and I'm not seeing any difference in behaviour. Currently my login is pretty much a carbon copy of the example login code, with an added couple of permissions.

**Comment by guilhermedecampo** [comment]
Also having this issue @crosstechnology. =(

**Comment by wafcross** [comment]
good to know im not the only one!

Just for a bit of added insight.. my facebook app status is 'pending status & review', presumably because of the added iOS stuff. I'm wondering if even though deep linking is enabled, it doesn't start working until that review is approved and accepted?

The only issue with this is that our app is still in development phase. I cannot provide an app store ID because it's not on the store yet, and it wants me to submit the app via a .zip folder but because the app is still in development even if I uploaded my .ipa file they wouldn't be able to view it because they aren't authorised on the list of app-users for the iOS developers system.

Could this cause the deep-linking to not actually work? All I really want is a simple flow:

user taps login button > if native FB app is installed on device - open a popup requesting the permissions/or redirect to FB app > if native FB app is not installed then im happy for it to open safari

Once again, any assistance that can be provided is greatly appreciated!

**Comment by guilhermedecampo** [comment]
Hello guys.
So this was my setup for this problem:

File `MYAPP-Info.plist` under Resources folder

Along with my 

```
<key>FacebookAppID</key>
<string>XXXXXXX</string>
<key>FacebookDisplayName</key>
<string>XXXXXX</string>
```

I added:

```
<!-- URLSchemes -->
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>xxxxxxxxxx</string>
    </array>
  </dict>
</array>
```

I don't know if this part bellow helped but my app is not prepared for 
full SSL connection yet.

```
<!-- Allow http connections -->
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
```

Then in my facebook dashboard,  I added the iOS platform and completed with only my bundle ID. 

Hope this helps someone!

**Comment by crosstechnology** [comment]
@guilhermedecampo thank you thank you thank you!!!!

my NSAppTransPortSecurity was already set to allow Arbitrary Loads, however settings the CFBundleURLSchemes appears to have resolved this :+1:
--------

This is only one-half of the equation though... Via this method my app is now opening a popup display prompting the user to login, which is fantastic because it's no longer redirecting to Safari.

The next step that I would LOVE to get working is if it can detect wether the native facebook App is installed, and if so pull the request straight from the native facebook app instead of prompting a login through the popup. I hope this make sense and thank you so much for your assistance thus far!

**Comment by aogilvie** [comment]
@crosstechnology 

>detect wether the native facebook App is installed, and if so pull the request straight from the native facebook app instead of prompting a login through the popup.

This is done for you in the FB SDK. It should only prompt a login the first time the user bounces between your app and FB.
