### ISSUE TITLE
I couldn't get the plugin to work

### ISSUE THREAD

**Issue by Dineshrajaa** [Wizcorp/phonegap-facebook-plugin#1154]
Hello,I am tryng to use this plugin for integrating Facebook login but I am getting the following error

"Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. To use this URL you must add a valid native platform in your App's settings.
![screenshot_2015-10-21-12-28-47](https://cloud.githubusercontent.com/assets/7291567/10630010/4bf62a5c-77f1-11e5-80ab-390602779a80.png)
"

**Comment by Dineshrajaa** [comment]
The problem was I didn't configure the FB app properly now I have solved it

**Comment by javicaballero** [comment]
How did you solve? can you send an example of your FB app settings please? Thanks!

**Comment by Dineshrajaa** [comment]
@javicaballero 
You have to create Android Hash key in your machine and add it in the FB app settings and you must give a redirect URL like http://www.localhost.com/callback.

**Comment by javicaballero** [comment]
Thank you Dineshrajaa, it works now!

**Comment by Dineshrajaa** [comment]
Welcome @javicaballero  :)

**Comment by artiberde27** [comment]
@Dineshrajaa ,@javicaballero
I am also facing the same issue.I have created an Android hash key and added it to FB app under Developer setting->sample app section and did save changes and it shows a notification that changes is saved but next time I visited that same section it didn't display my hash key.The text box was empty.Am I  missing something while setting key?And how to set redirect URL as there is no domain because I am building an app using PhoneGap.

Thanks
