### ISSUE TITLE
How to post photo with Graph API

### ISSUE THREAD

**Issue by phuongtailtranminh** [Wizcorp/phonegap-facebook-plugin#1210]
Hi,

I'm trying to figure out how to use POST method to post  a photo via Facebook Graph API.

https://developers.facebook.com/docs/graph-api/reference/user/photos/

Any idea for this?

**Comment by dantabel** [comment]
I had to clone and add my own functionality. I actually cloned [a fork](https://github.com/jeduan/cordova-plugin-facebook4) of this repo but here's my code. You can then use `FacebookConnectPlugin.apiPost(path, permissions, postData, success, failure)` instead of `FacebookConnectPlugin.api(path, permissions, success, failure)`
https://github.com/dantabel/cordova-plugin-facebook4

**Comment by junerockwell** [comment]
@dantabel Can your version post an image from the app's local folders instead of a remote image? The image can be in a local SQLite DB or in a `www` folder in Ionic/Cordova.
