### ISSUE TITLE
Login does not return user data

### ISSUE THREAD

**Issue by srameshr** [Wizcorp/phonegap-facebook-plugin#816]
I have set the hash key. Can someone please share some code, that returns user public profile data and email when they log in ?

Every time that I do login, I just get userId and some other data.

**Comment by MindandMedia** [comment]
I've tried to use the  facebookConnectPlugin.api('/me', ['public_profile', 'email'],
successCallBack, errorCallback); after a successful login (as described above), but instead of returning the requested information, I am presented with a dialog to confirm i've already granted permissions, and nothing is returned.  When I attempt to call the  api again (via click event like in the examples), I get a message indicating that "an attempt was made to request new permissions for a session that has a pending request."

Please advise.

Thanks
