### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by hsmith825** [Wizcorp/phonegap-facebook-plugin#905]
I am using Xcode 6.1.1 and cordova 3.5.  I installed the latest Facebook plugin on from a local clone (as directed) to my app that previously worked in Cordova 3.5.  I get the following error:  Undefined symbols for architecture x86_64. 

Any ideas on how to solve this problem?

Thanks!
hsmith825

**Comment by aogilvie** [comment]
@hsmith825 which symbols? Paste the entire error output / Xcode error page.

**Comment by hsmith825** [comment]
Here is what I know about the problem now.  I build successfully and successfully login with the Facebook credentials.  I then use the graph api as follows: facebookConnectPlugin.api(wuserid +"/?fields=name,picture,email,first_name, age_range,currency,languages",["user_birthday"],function (response) {my code}, function (error) {
            alert("Failed: " + error);}.
The error I get from Facebook is Failed.  The operation couldn't be completed. (com.facebook.sdk error5.).  The operation couldn’t be completed. (com.facebook.sdk error 5.).  This worked until recently with no changes to the Facebook code.
Any suggestions are appreciated.
Thanks aogilvie

**Comment by aogilvie** [comment]
@hsmith825 This can happen for many reasons, you will need to do 2 things;
1) create a new issue because this is now off topic.
2) post all the console logs you have (usually error 5 is a generic error you need to examine more closely the http request code result from the FB SDK. It could be anything from FB blocking multiple requests thinking you are spam or FB was down for some reason.. etc.)
