### ISSUE TITLE
Cordova Facebook login method issues

### ISSUE THREAD

**Issue by Yashaswini** [Wizcorp/phonegap-facebook-plugin#928]
Hello , 
I am facing issue using this plugin. Looking forward some help since I have been stuck with this since yesterday. 
I am working for a phonegap app built on Ionic framework. When i make a call to $CordovaFacebook.login() , i get these two errors: 
1. Facebook-publish( 2132): FacebookException: No attribution id available to send to server.
2. ActivityThread( 2132): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider

Could you help me dig through this? 
Thanks in Advance !!

**Comment by aogilvie** [comment]
@Yashaswini Is it crashing? Or you are just concerned about these messages?

In Android you will see `Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider` log produced when the Facebook SDK looks for the official Facebook SDK, if it cannot find this deep link then it will use the WebDialogs to display the login UI.

`FacebookException: No attribution id available to send to server.` is logged by the Facebook SDK i believe because you are not logged in and there is no official Facebook application on your device.
You can see a reference to this in the Facebook documentation.

https://developers.facebook.com/docs/reference/android/current/class/Facebook/

```
Attribution ID that will be used for conversion tracking. It will be null only if the user has not installed or logged in to the Facebook app.
```

**Comment by Yashaswini** [comment]
@aogilvie Thanks a lot for quick reply. 

This is how my adb log cat console looks. This is after i give my credentials to facebook app. 
Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
E/eglCodecCommon( 3393): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 3393): **** ERROR unknown type 0x0 (glSizeof,72)
D/CordovaActivity( 3393): Incoming Result
D/CordovaActivity( 3393): Request code = 64206
D/CordovaActivity( 3393): We have a callback to send this result to
D/ConnectPlugin( 3393): activity result in plugin: requestCode(64206), resultCode(-1)
D/com.facebook.Session( 3393): Unexpected call to finishAuthOrReauth in state CLOSED
D/CordovaActivity( 3393): Resuming the App
E/ActivityThread( 3393): Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
D/Facebook-publish( 3393): FacebookException: No attribution id available to send to server.

I am not able to receive success object. Any idea why this is hapenning?

**Comment by aogilvie** [comment]
@Yashaswini 
Can you check the following:

- Are you connected to the internet
- Have you given permission for internet access (AndroidManifest.xml)
- Have you used a correct hashkey for the app
- Is your App Id correct (if you used CLI is should be in res/strings/facebookconnect.xml)
